---
grails:
    profile: web
    codegen:
        defaultPackage: letters
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    plugin:
        databasemigration:
            changelogLocation: 'grails-app/migrations'
            changelogFileName: 'changelog.groovy'
            updateOnStart: true
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

dataSource:
    pooled: true
    jmxExport: true
    dbCreate: ''

---
environments:
    development:
        dataSource:
            dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
            driverClassName: 'com.mysql.jdbc.Driver'
            url: 'jdbc:mysql://localhost:3306/letters_development'
            username: 'letters'
            password: 'letters'
            logSql: false
        plugin:
            fields:
                disableLookupCache: true
    test:
        plugin:
            databasemigration:
                changelogLocation: 'grails-app/migrations'
                changelogFileName: 'changelog.groovy'
                updateOnStart: true
        dataSource:
            dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
            driverClassName: 'com.mysql.jdbc.Driver'
            url: 'jdbc:mysql://localhost:3306/letters_test'
            username: 'letters'
            password: 'letters'
            logSql: false
    production:
        plugin:
            databasemigration:
                changelogLocation: 'grails-app/migrations'
                changelogFileName: 'changelog.groovy'
                updateOnStart: true
        dataSource:
            dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
            driverClassName: 'com.mysql.jdbc.Driver'
            url: 'jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}'
            username: '${MYSQL_USER}'
            password: '${MYSQL_PASSWORD}'
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: 'SELECT 1'
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: 'ConnectionState'
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        server:
            port: 8888
---
server:
    tomcat:
        remote_ip_header: 'x-forwarded-for'
        protocol_header: 'x-forwarded-proto'